# Generated by Django 4.1.4 on 2022-12-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_seller_review_commenter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='commenter',
            new_name='reviewer',
        ),
    ]
